path_constraint:
  name: flat_gripper
  constraints:
#  - type: orientation
#    frame_id: world #change
  - type: joint
    joint_name: first_joint #change
    position: 0.1
    tolerance: 0.2 
#   or tolerances: [0.1, 0.2]
#    bounds: [-0.5, 1.0] # instead of pos+tol	
    weight: 1.0

  - type: orientation
    frame_id: base_link
    link_name: gripper_link
    orientation: [-3.1415269, -1.57079632, 0] #RPY
    tolerances: [6.28318531, 0.2, 6.28318531]
    weight: 1.0

# https://ros-planning.github.io/moveit_tutorials/doc/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.html

#https://github.com/ros-planning/moveit/blob/master/moveit_planners/ompl/ompl_interface/launch/generate_state_database.launch

#https://docs.ros.org/en/noetic/api/moveit_core/html/cpp/classkinematic__constraints_1_1VisibilityConstraint.html#details

#https://docs.ros.org/en/noetic/api/moveit_planners_ompl/html/classompl__interface_1_1ConstraintsLibrary.html
